name: Djalal
favicon: null
layout_spectrum: 0.33423941233195364
typography_spectrum: 0.22590364841744304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9087300966493785
  lightness: 0.31842922791838646
  saturation: 0.3700100651476532
  rhythmicContrast: 0.0995674068108201
purpose: []
